context:
  version: 1.1.0
package:
  name: "robin"
  version: '{{ version }}'

source:
  path: .

requirements:
  build:
    - go

build:
  script:
    - env CGO_ENABLED=0 go build -o ${PREFIX}/bin/robin ./cmd/robin