Name = "count_oranges"
Type = "simple"

Walltime = "30m"

Nodes = 2
TasksPerNode = 4

NodeType = "rome"
Queue = "test"

Email = "spanner@unkaktus.art"

InitScript = [
    "module load apptainer"
    ]

Runtime = [
    "apptainer",
    "exec",
    "--bind /work:/work",
    "--bind /scratch:/scratch",
    ]
Executable = "~/apptainers/count-oranges.sif"
Arguments = [
    "--config={{.ConfigFilename}}",
    "--total-task-number={{.TotalTaskNumber}}",
    "--task-id={{.TaskID}}"
    ]